game/gallows/lib/gallows_web/router.ex
defmodule GallowsWeb.Router do
  use GallowsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/hangman", GallowsWeb do
    pipe_through :browser

    get "/", HangmanController, :new_game
    post "/", HangmanController, :create_game
  end

  # Other scopes may use custom stacks.
  # scope "/api", GallowsWeb do
  #   pipe_through :api
  # end
end

game/gallows/lib/gallows/application.ex
defmodule Gallows.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the endpoint when the application starts
      GallowsWeb.Endpoint
      # Starts a worker by calling: Gallows.Worker.start_link(arg)
      # {Gallows.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Gallows.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    GallowsWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

game/gallows/lib/gallows_web/controllers/hangman_controller.ex
defmodule GallowsWeb.HangmanController do
  use GallowsWeb, :controller

  def new_game(conn, _params) do
    render(conn, "new_game.html")
  end

  def create_game(conn, _params) do
    game = Hangman.new_game()
    tally = Hangman.tally(game)
    conn
    |> put_session(:game, game)
    |> render("game_field.html", tally: tally)
  end
end

game/gallows/lib/gallows_web/views/error_view.ex
defmodule GallowsWeb.ErrorView do
  use GallowsWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

game/gallows/lib/gallows_web/views/hangman_view.ex
defmodule GallowsWeb.HangmanView do
  use GallowsWeb, :view
end

game/gallows/lib/gallows_web/views/layout_view.ex
defmodule GallowsWeb.LayoutView do
  use GallowsWeb, :view
end

game/gallows/lib/gallows_web/templates/hangman/game_field.html.eex
<%= inspect @tally%>

<p>
  Turns Left: <%= @tally.turns_left%>
</p>

<p>
  Word so far: <%= @tally.letters |> Enum.join(" ")%>
</p>

<form>

</form>

game/gallows/lib/gallows_web/templates/hangman/new_game.html.eex
<h1>Welcome to Hangman!</h1>
<%= button("New Game", to: Routes.hangman_path(@conn, :create_game)) %>

game/gallows/lib/gallows_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= assigns[:page_title] || "Hangman" %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <main role="main" class="container">
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>